spring:
  datasource:
    url: jdbc:h2:mem:librarydb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      # Dejar ddl-auto en 'update' para no borrar datos en cada arranque en desarrollo.
      # Para que data.sql (scripts de import) se ejecute después de que Hibernate crea/actualice el esquema,
      # activamos 'defer-datasource-initialization'. Esto evita el error "Table not found".
      ddl-auto: update
    # Hace que la ejecución de script de SQL (data.sql) se difiera hasta que JPA haya inicializado el esquema.
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
  # Configuración de inicialización de SQL: asegurar UTF-8 para scripts con caracteres acentuados.
  sql:
    init:
      encoding: UTF-8
  application:
    name: apirest
server:
  port: 8080

security:
  auth:
    registration-enabled: true
  jwt:
    secret: ${SECURITY_JWT_SECRET:changemechangemechangemechangeme}
    issuer: apirest
    access-ttl: 15m
    refresh-ttl: 7d
    refresh-enabled: true
    denylist-enabled: false
  cors:
    allowed-origins:
      - http://localhost:3000
logging:
  level:
    org.hibernate.SQL: DEBUG           # Muestra SQL ejecutado
    org.hibernate.orm.jdbc.bind: TRACE # Muestra parámetros enlazados
    org.hibernate.tool.schema: DEBUG   # Mensajes del generador de esquema (DDL)
    org.hibernate.orm.schema: DEBUG    # Logs adicionales de schema en Hibernate 6